name: 'Install Dependencies'
description: 'Installs dependencies'

inputs:
  cache-key:
    description: 'Cache key'
    required: true

runs:
  using: 'composite'
  steps:
    
    - name: Check cache
      id: check-cache
      uses: actions/cache@v3
      with:
        path: |
          C:\ProgramData\chocolatey\lib\ninja\tools
          C:\Program Files\OpenCppCoverage
        key: ${{ inputs.cache-key }}-${{ hashFiles('.github/workflows/actions/deps/action.yml') }}
        lookup-only: true 
        restore-keys: |
          ${{ inputs.cache-key }}-
        enableCrossOsArchive: true

    - name: Install Ninja
      if: steps.check-cache.outputs.cache-hit != 'true'
      shell: pwsh
      run: |
        choco install ninja
    
    - name: Download OpenCppCoverage
      id: download-opencppcoverage
      if: steps.check-cache.outputs.cache-hit != 'true'
      shell: pwsh
      run: |
        choco install opencppcoverage

    - name: Save cache
      if: steps.check-cache.outputs.cache-hit != 'true'
      uses: actions/cache/save@v3
      with:
        path: |
          C:\ProgramData\chocolatey\lib\ninja\tools
          C:\Program Files\OpenCppCoverage
        key: ${{ inputs.cache-key }}-${{ hashFiles('.github/workflows/actions/deps/action.yml') }}
        enableCrossOsArchive: true
