name: 'SonarCloud Analysis'
description: 'Runs SonarCloud analysis with test coverage'

inputs:
  build-dir:
    description: 'CMake build directory'
    required: true
  sonar-token:
    description: 'SonarCloud token'
    required: true
  cache-key:
    description: 'Cache key prefix'
    required: true

runs:
  using: "composite"
  steps:
    - name: Restore Build Cache
      uses: actions/cache/restore@v3
      with:
        path: |
          ${{ inputs.build-dir }}
          ${{ inputs.build-dir }}/CMakeCache.txt
          ${{ inputs.build-dir }}/CMakeFiles
          ${{ inputs.build-dir }}/_deps
        key: ${{ inputs.cache-key }}-tests

        
    - name: Prepare coverage reports
      shell: pwsh
      run: |
        $coverage_dir = "${{ inputs.build-dir }}\bin\coverage"
        if (Test-Path $coverage_dir\final.xml) {
            Write-Host "Coverage report found at $coverage_dir\final.xml with content: $(Get-Content $coverage_dir\final.xml)"
        } else {
            Write-Host "No coverage report found"
        }

    - name: Find compile commands
      shell: pwsh
      run: |
        $compile_commands = Get-ChildItem -Path ${{ inputs.build-dir }} -Filter compile_commands.json
        Write-Host "Compile commands found at $compile_commands"

    - name: Run SonarCloud analysis
      env:
        SONAR_TOKEN: ${{ inputs.sonar-token }}
      uses: SonarSource/sonarqube-scan-action@v5
