name: 'Setup CMake'
description: 'Sets up CMake build environment and caching'

inputs:
  build-dir:
    description: 'CMake build directory'
    required: true
outputs:
  lint-report:
    description: 'Lint report'

runs:
  using: composite
  steps:  
    - name: Configure CMake
      shell: pwsh
      run: |
        if (-not (Test-Path -Path ${{ inputs.build-dir }})) {
            New-Item -ItemType Directory -Path ${{ inputs.build-dir }} -Force
        }
        cmake -B ${{ inputs.build-dir }} -DCMAKE_BUILD_TYPE=Release -DQUALITY_ONLY=ON

    - name: Check Format
      shell: pwsh
      run: cmake --build ${{ inputs.build-dir }} --target format-check
    
    - name: Run Lint Check
      shell: pwsh
      continue-on-error: true
      run: cmake --build ${{ inputs.build-dir }} --target lint-check

    - name: Analyze Lint Results
      shell: pwsh
      run: |
        cat ${{ inputs.build-dir }}/lint-reports/report.txt
        cmake --build ${{ inputs.build-dir }} --target lint-analyze
