name: 'Setup CMake'
description: 'Sets up CMake build environment and caching'

inputs:
  github-token:
    description: 'GitHub token for authentication'
    required: true
  cache-prefix:
    description: 'Prefix for cache keys'
    required: true
  build-dir:
    description: 'CMake build directory'
    required: true


runs:
  using: "composite"
  steps:  
    - name: Restore CMake cache
      uses: actions/cache/restore@v3
      with:
        path: |
          ${{ inputs.build-dir }}
          ${{ inputs.build-dir }}/CMakeCache.txt
          ${{ inputs.build-dir }}/CMakeFiles
          ${{ inputs.build-dir }}/_deps
        key: ${{ inputs.cache-prefix }}-${{ runner.os }}-cmake-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}
        restore-keys: |
          ${{ inputs.cache-prefix }}-${{ runner.os }}-cmake-
    
    - name: Configure CMake
      shell: pwsh
      run: |
        cmake -B ${{ inputs.build-dir }} -DCMAKE_BUILD_TYPE=Release -DGITHUB_TOKEN=${{ inputs.github-token }}

    - name: Check Format
      shell: pwsh
      run: cmake --build ${{ inputs.build-dir }} --target format-check
    
    - name: Run Lint Check
      shell: pwsh
      run: cmake --build ${{ inputs.build-dir }} --target lint-check

    - name: Analyze Lint Results
      shell: pwsh
      run: |
        cat ${{ inputs.build-dir }}/lint-reports/report.txt
        cmake --build ${{ inputs.build-dir }} --target lint-analyze
        
