name: 'Setup CMake'
description: 'Sets up CMake build environment and caching'

inputs:
  github-token:
    description: 'GitHub token for authentication'
    required: true
  cache-prefix:
    description: 'Prefix for cache keys'
    required: true
  build-dir:
    description: 'CMake build directory'
    required: true
outputs:
  lint-report:
    description: 'Lint report'

runs:
  using: composite
  steps:  
    - name: Configure CMake
      shell: bash
      run: |
        cmake -B ${{ inputs.build-dir }} -DCMAKE_BUILD_TYPE=Release -DGITHUB_TOKEN=${{ inputs.github-token }} -DQUALITY_ONLY=ON

    - name: Check Format
      shell: bash
      run: cmake --build ${{ inputs.build-dir }} --target format-check
    
    - name: Run Lint Check
      shell: bash
      continue-on-error: true
      run: cmake --build ${{ inputs.build-dir }} --target lint-check

    - name: Analyze Lint Results
      shell: bash
      run: |
        cat ${{ inputs.build-dir }}/lint-reports/report.txt
        cmake --build ${{ inputs.build-dir }} --target lint-analyze

    - name: Read lint report
      shell: bash
      run: |
        cat ${{ inputs.build-dir }}/lint-reports/github-report.txt

    - name: Set output
      shell: bash
      run: echo "lint-report=$(cat ${{ inputs.build-dir }}/lint-reports/github-report.txt)" >> $GITHUB_OUTPUT
