name: 'Restore Dependencies'
description: 'Restores cached build dependencies'

inputs:
  cache-key:
    description: 'Cache prefix'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Restore Chocolatey packages
      uses: actions/cache/restore@v3
      with:
        path: |
          C:\ProgramData\chocolatey\lib\ninja\tools
          C:\Program Files\OpenCppCoverage
        key: ${{ inputs.cache-key }}-${{ hashFiles('.github/workflows/actions/deps/action.yml') }}
        restore-keys: |
          ${{ inputs.cache-key }}-
        enableCrossOsArchive: true

        
    - name: Set path
      shell: pwsh
      run: |
        $env:PATH = "$env:PATH;C:\ProgramData\chocolatey\lib\ninja\tools;C:\Program Files\OpenCppCoverage"
