function(copy_curl_libs)
    message(STATUS "Copying curl libraries")
    if(CURL_BINARY_DIR)
        message(STATUS "CURL_BINARY_DIR: ${CURL_BINARY_DIR}")
        if(WIN32)
            # don't fail if the files don't exist
            if(EXISTS ${CURL_BINARY_DIR}/lib/libcurl.dll)
                file(COPY ${CURL_BINARY_DIR}/lib/libcurl.dll DESTINATION ${CMAKE_BINARY_DIR}/bin)
            elseif(EXISTS ${CURL_BINARY_DIR}/lib/libcurl-d.dll)
                file(COPY ${CURL_BINARY_DIR}/lib/libcurl-d.dll DESTINATION ${CMAKE_BINARY_DIR}/bin)
            else()
                message(WARNING "No curl.dll or libcurl-d.dll found in ${CURL_BINARY_DIR}/lib")
            endif()
        endif()
        if(APPLE)
            # don't fail if the files don't exist
            if(EXISTS ${CURL_BINARY_DIR}/lib/libcurl.dylib)
                file(COPY ${CURL_BINARY_DIR}/lib/libcurl.dylib DESTINATION ${CMAKE_BINARY_DIR}/lib)
            endif()
            if(EXISTS ${CURL_BINARY_DIR}/lib/libcurl-d.dylib)
                file(COPY ${CURL_BINARY_DIR}/lib/libcurl-d.dylib DESTINATION ${CMAKE_BINARY_DIR}/lib)
            endif()
        endif()
    else()
        message(WARNING "CURL_BINARY_DIR is not set. It can mean that curl is installed on system, so no copy is needed.")
    endif()    
endfunction(copy_curl_libs)

function(copy_sauron_sdk_libs)
    message(STATUS "Copying sauron sdk libraries")
    if(Sauron-SDK_BINARY_DIR)
        message(STATUS "Sauron-SDK_BINARY_DIR: ${SAURO_SDK_BINARY_DIR}")
        if(WIN32)
            # don't fail if the files don't exist
            if(EXISTS ${Sauron-SDK_BINARY_DIR}/sauron-sdk-curl/sauron-sdk-curl.dll)
                file(COPY ${Sauron-SDK_BINARY_DIR}/sauron-sdk-curl/sauron-sdk-curl.dll DESTINATION ${CMAKE_BINARY_DIR}/bin)
            else()
                message(WARNING "No sauron-sdk-curl.dll found in ${Sauron-SDK_BINARY_DIR}/sauron-sdk-curl")
            endif()
        endif()
        if(APPLE)
            # don't fail if the files don't exist
            if(EXISTS ${Sauron-SDK_BINARY_DIR}/sauron-sdk-curl/libsauron-sdk-curl.dylib)
                file(COPY ${Sauron-SDK_BINARY_DIR}/sauron-sdk-curl/libsauron-sdk-curl.dylib DESTINATION ${CMAKE_BINARY_DIR}/lib)
            else()
                message(WARNING "No libsauron-sdk-curl.dylib found in ${Sauron-SDK_BINARY_DIR}/sauron-sdk-curl")
            endif()
        endif()
    else()
        message(WARNING "Sauron-SDK_BINARY_DIR is not set")
    endif()
endfunction(copy_sauron_sdk_libs)
