# Main workflow for building and checking code quality
name: Build

# Trigger the workflow on push and pull request events for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches:
      - '**'

# Add required permissions
permissions:
  contents: read
  pull-requests: write
  issues: write

# Prevent multiple workflows from running simultaneously on the same ref
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Global environment variables
env:
  FORCE_COLOR: 1  # Enable colored output in logs
  TERM: xterm-256color  # Terminal type for better formatting
  CMAKE_BUILD_DIR: ${{ github.workspace }}/build
  CACHE_KEY_PREFIX: v1  # Increment this to invalidate all caches
jobs:
  install-deps:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        uses: ./.github/workflows/actions/deps
        with:
          cache-key: ${{ env.CACHE_KEY_PREFIX }}-${{ runner.os }}-deps-${{ hashFiles('.github/workflows/actions/deps/action.yml') }}
  # Build the project on both platforms
  build:
    needs: [install-deps]
    name: Build-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false  # Don't cancel other platforms if one fails
      matrix:
        os: [windows-latest] #, macos-latest]  # Macos is to costly for private builds
        include:
          # Windows-specific settings
          - os: windows-latest
            #artifact_name: Palantir-Windows
            #artifact_path: build/Release/Palantir.exe
          # macOS-specific settings
          #- os: macos-latest
            #artifact_name: Palantir-macOS
            #artifact_path: build/Palantir.app
            #use_quality_build: true
    
    steps:
      - uses: actions/checkout@v4
      - name: Restore dependencies
        uses: ./.github/workflows/actions/restore-deps
        with:
          cache-key: ${{ env.CACHE_KEY_PREFIX }}-${{ runner.os }}-deps-${{ hashFiles('.github/workflows/actions/deps/action.yml') }}
      - name: Build
        uses: ./.github/workflows/actions/build
        with:
          build-dir: ${{ env.CMAKE_BUILD_DIR }}
          cache-key: ${{ env.CACHE_KEY_PREFIX }}-${{ runner.os }}-cmake-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}-${{ github.ref }}

  tests:
    needs: [build]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Restore dependencies
        uses: ./.github/workflows/actions/restore-deps
        with:
          cache-key: ${{ env.CACHE_KEY_PREFIX }}-${{ runner.os }}-deps-${{ hashFiles('.github/workflows/actions/deps/action.yml') }}
      - name: Run Tests
        uses: ./.github/workflows/actions/tests
        with:
          build-dir: ${{ env.CMAKE_BUILD_DIR }}
          cache-key: ${{ env.CACHE_KEY_PREFIX }}-${{ runner.os }}-cmake-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}-${{ github.ref }}

  sonar-analysis:
    needs: [tests]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Important for Sonar analysis
      - name: Run Sonar Analysis
        uses: ./.github/workflows/actions/sonar
        with:
          build-dir: ${{ env.CMAKE_BUILD_DIR }}
          sonar-token: ${{ secrets.SONAR_TOKEN }}
          cache-key: ${{ env.CACHE_KEY_PREFIX }}-${{ runner.os }}-cmake-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}-${{ github.ref }}

  clear-run-caches:
    name: Clear Run Caches
    needs: [sonar-analysis]  # Changed to run after sonar analysis
    if: always()
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Clear Run Caches
        uses: ./.github/workflows/actions/clear-run-caches
        with:
          github-token: ${{ secrets.PALANTIR_GHA }}
          build-dir: ${{ env.CMAKE_BUILD_DIR }}
          cache-key: ${{ env.CACHE_KEY_PREFIX }}-${{ runner.os }}-cmake-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}-${{ github.ref }}
