name: cleanup caches by a branch
on:
  issue_comment:
    types: [created]

jobs:
  cleanup:
    if: (github.event_name == 'issue_comment' && github.event.comment.body == 'clear caches')
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup
        run: |
          echo "Fetching list of cache key"
          cacheKeysForPR=$(gh cache list --ref $BRANCH --json id --jq '.[].id')

          ## Setting this to not fail the workflow while deleting cache keys.
          set +e
          echo "Deleting caches..."
          for cacheKey in $cacheKeysForPR
          do  
            if [[ $cacheKey != *"deps"* ]]; then
              gh cache delete $cacheKey
            fi
          done
          echo "Done"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          BRANCH: refs/pull/${{ github.event.issue.number }}/merge
