# Main workflow for building and checking code quality
name: Code Quality PR

# Trigger the workflow on push and pull request events for the master branch
on:
  issue_comment:
    types: [created]

# Add required permissions
permissions:
  contents: read
  pull-requests: write
  issues: write
  checks: write  # Add this permission for check runs

# Global environment variables
env:
  FORCE_COLOR: 1  # Enable colored output in logs
  TERM: xterm-256color  # Terminal type for better formatting
  CMAKE_BUILD_DIR: ${{ github.workspace }}/build

jobs:
  code-quality:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request && github.event.comment.body == 'run code quality'
    steps:
      - name: Get PR data
        id: pr
        uses: ./.github/workflows/actions/get-pr-data
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create in-progress check
        uses: ./.github/workflows/actions/check-run
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          sha: ${{ steps.pr.outputs.sha }}
          status: 'in_progress'

      - uses: actions/checkout@v4
        with:
          ref: refs/pull/${{ github.event.issue.number }}/head
          fetch-depth: 0

      - uses: ./.github/workflows/actions/quality
        id: quality
        with:
          build-dir: ${{ env.CMAKE_BUILD_DIR }}
          files: ${{ steps.pr.outputs.files }}

      - name: Read lint report
        id: lint_report
        shell: bash
        continue-on-error: true
        run: |
          REPORT_CONTENT=$(cat ${{ env.CMAKE_BUILD_DIR }}/lint-reports/github-report.txt)
          echo "report<<EOF" >> $GITHUB_OUTPUT
          echo "$REPORT_CONTENT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      
      - name: Comment lint report
        uses: ./.github/workflows/actions/comment-report
        continue-on-error: true
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          report: ${{ steps.lint_report.outputs.report }}

      - name: Update check status
        if: always()
        uses: ./.github/workflows/actions/check-run
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          sha: ${{ steps.pr.outputs.sha }}
          status: 'completed'
          conclusion: ${{ steps.quality.outcome }}
