# Main workflow for building and checking code quality
name: Code Quality Master

# Trigger the workflow on push and pull request events for the master branch
on:
  push:
    branches: [ master ]

# Add required permissions
permissions:
  contents: read
  pull-requests: write
  issues: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

# Global environment variables
env:
  FORCE_COLOR: 1  # Enable colored output in logs
  TERM: xterm-256color  # Terminal type for better formatting
  CMAKE_BUILD_DIR: ${{ github.workspace }}\build

jobs:
  code-quality:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/actions/quality
        with:
          build-dir: ${{ env.CMAKE_BUILD_DIR }}
