# Main workflow for building and checking code quality
name: Code Quality PR

# Trigger the workflow on push and pull request events for the master branch
on:
  issue_comment:
    types: [created]

# Add required permissions
permissions:
  contents: read
  pull-requests: write
  issues: write

# Global environment variables
env:
  FORCE_COLOR: 1  # Enable colored output in logs
  TERM: xterm-256color  # Terminal type for better formatting
  CMAKE_BUILD_DIR: ${{ github.workspace }}/build
  CACHE_KEY_PREFIX: v1  # Increment this to invalidate all caches

jobs:
  code-quality:
    runs-on: windows-latest
    if: github.event.issue.pull_request && github.event.comment.body == 'run code quality'
    steps:
      - name: Create in-progress check
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: 'Code Quality Check',
              head_sha: context.payload.comment.commit_id,
              status: 'in_progress',
              started_at: new Date()
              token: ${{ secrets.PALANTIR_GHA }}
            })

      - uses: actions/checkout@v4
        with:
          ref: refs/pull/${{ github.event.issue.number }}/head
          fetch-depth: 0

      - uses: ./.github/workflows/actions/quality
        id: quality
        with:
          github-token: ${{ secrets.PALANTIR_GHA }}
          cache-prefix: ${{ env.CACHE_KEY_PREFIX }}
          build-dir: ${{ env.CMAKE_BUILD_DIR }}

      - name: Update check status
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const conclusion = '${{ steps.quality.outcome }}' === 'success' ? 'success' : 'failure';
            github.rest.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: 'Code Quality Check',
              head_sha: context.payload.comment.commit_id,
              status: 'completed',
              conclusion: conclusion,
              completed_at: new Date()
              token: ${{ secrets.PALANTIR_GHA }}
            })
